version = 0.1

[default.local_start_api.parameters]
port = 8082
warm-containers = "EAGER"
env_vars = "sam-local-env-vars.json"

[default.local_invoke.parameters]
port = 8082
warm-containers = "EAGER"
env_vars = "sam-local-env-vars.json"