AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Card Service - Serverless (Lambda + API Gateway)

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: java17
    Architectures: [x86_64]
    Environment:
      Variables:
        SPRING_PROFILES_ACTIVE: lambda-local
        DEPENDENCY_CHECK_SKIP: ''
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
#        FUNCTION_RESOURCE_TYPE: http

Parameters:
  ShadedJarName:
    Type: String
#    Default: card-service-0.0.1-SNAPSHOT-lambda.jar
    Default: card-service-lambda.jar
    Description: Name of the shaded JAR in target/

Resources:
  CardServiceAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
#      Handler: org.springframework.cloud.function.adapter.aws.FunctionStreamHandler
#      Handler: com.portfolio.banking.StreamLambdaHandler
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
#      CodeUri: .
#      CodeUri: target/card-service-0.0.1-SNAPSHOT.jar
#      CodeUri: target/card-service-lambda.jar
      CodeUri: !Sub "target/${ShadedJarName}"
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          spring.cloud.function.definition: lambdaRouter
          AWS_DYNAMODB_ENDPOINT: !ImportValue banking-portfolio-core:DynamoDBTable
          MAIN_CLASS: com.portfolio.banking.cardservice.CardServiceApplication
      Events:
        IssueVCN:
          Type: Api
          Properties:
            Path: /cards/vcn
            Method: post
            RestApiId: !Ref CardServiceApi
        GetRealCard:
          Type: Api
          Properties:
            Path: /cards/real
            Method: get
            RestApiId: !Ref CardServiceApi
        GetVCNs:
          Type: Api
          Properties:
            Path: /cards/vcns
            Method: get
            RestApiId: !Ref CardServiceApi

  CardServiceAccountCreatedListenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      CodeUri: !Sub "target/${ShadedJarName}"
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          spring.cloud.function.definition: accountCreated
          AWS_DYNAMODB_ENDPOINT: !ImportValue banking-portfolio-core:DynamoDBTable
          MAIN_CLASS: com.portfolio.banking.cardservice.CardServiceApplication
      Events:
        AccountCreated:
#          Type: Kafka
          Type: SelfManagedKafka
          Properties:
            BootstrapServers: "host.docker.internal:9092"
            Topics:
              - account-created
            ConsumerGroupId: card-group
            StartingPosition: LATEST
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 5

  CardServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization'"
        AllowMethods: "'GET,POST,OPTIONS'"
    Name: !Sub "${AWS::StackName}-api"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*!ImportValue banking-portfolio-core:DynamoDBTable*"

  Resources:
    CardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Cards
        AttributeDefinitions:
          - AttributeName: cardId
            AttributeType: S
        KeySchema:
          - AttributeName: cardId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    VirtualCardTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VirtualCardTokens
        AttributeDefinitions:
          - AttributeName: tokenId
            AttributeType: S
          - AttributeName: realCardId
            AttributeType: S
        KeySchema:
          - AttributeName: tokenId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: RealCardIdIndex
            KeySchema:
              - AttributeName: realCardId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

Outputs:
  CardServiceApiUrl:
    Description: API Gateway endpoint
    Value: !Sub "https://${CardServiceApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Export:
      Name: CardServiceLambdaApiUrl   # Used by EB stack