-- CREATE TABLE account (
--                          account_id VARCHAR(255) PRIMARY KEY,
--                          balance NUMERIC(15,2) NOT NULL
-- );
--
-- CREATE TABLE transfer (
--                           transfer_id VARCHAR(255) PRIMARY KEY,
--                           from_account_id VARCHAR(255) NOT NULL,
--                           to_account_id VARCHAR(255) NOT NULL,
--                           amount NUMERIC(15,2) NOT NULL,
--                           status VARCHAR(50) NOT NULL,
--                           created_at TIMESTAMP NOT NULL,
--                           updated_at TIMESTAMP NOT NULL,
--                           CONSTRAINT unique_transfer_id UNIQUE (transfer_id)
-- );

-- CREATE TABLE transaction (
--                              transaction_id VARCHAR(255) PRIMARY KEY,
--                              from_account_id VARCHAR(255),
--                              to_account_id VARCHAR(255),
--                              account_id VARCHAR(255),
--                              amount NUMERIC(15,2) NOT NULL,
--                              transaction_type VARCHAR(50) NOT NULL,
--                              status VARCHAR(50) NOT NULL,
--                              created_at TIMESTAMP NOT NULL,
--                              updated_at TIMESTAMP NOT NULL,
--                              CONSTRAINT unique_transaction_id UNIQUE (transaction_id)
-- );