spring:
  application:
    name: card-service
#  config:
#    import: "aws-parameterstore:/banking/backend/account-service/"
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
#  main:
#    web-application-type: none   # Critical for Lambda
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  cloud:
    function:
      definition: ${SPRING_CLOUD_FUNCTION_DEFINITION}
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      dynamodb:
        endpoint: ${AWS_DYNAMODB_ENDPOINT:}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true

account:
  service:
    url: http://${ACCOUNT_SERVICE_URL:localhost:8081}