spring:
  application:
    name: card-service
#  config:
#    import: "aws-parameterstore:/banking/backend/account-service/"
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
#  main:
#    web-application-type: none   # Critical for Lambda
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
  cloud:
    function:
      definition: ${SPRING_CLOUD_FUNCTION_DEFINITION}
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      dynamodb:
        endpoint: ${AWS_DYNAMODB_ENDPOINT:}
        enabled: true
    openfeign:
      micrometer:
        enabled: true
      okhttp:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        spring.kafka.listener: true
        spring.cloud.function: true
        http.client.requests: true
      slo:
        http.client.requests: 50ms,100ms,200ms,500ms,1s,5s
    enable:
      all: true
  tracing:
    enabled: false
    sampling:
      probability: 1.0
  observations:
    annotations:
      enabled: true
#  otlp:
#    logging:
#      export:
#        enabled: true
#      endpoint: ${ALLOY_BASE_URL:http://host.docker.internal:4318}
#    tracing:
#      export:
#        enabled: true
#      endpoint: ${ALLOY_BASE_URL:http://host.docker.internal:4318}
#    metrics:
#      export:
#        enabled: true
#        url: ${ALLOY_BASE_URL:http://host.docker.internal:4318}
#        step: 10s

#otel:
#  service:
#    name: card-service
#  exporter:
#    otlp:
#      endpoint: ${ALLOY_BASE_URL}
#      protocol: http/protobuf
#      timeout: 60000
#
#  # Configuration for the Batch Span Processor (Traces)
#  bsp:
#    schedule:
#      delay: 10 # (in ms)
#
#  # Configuration for the Batch Log Record Processor (Logs)
#  blrp:
#    schedule:
#      delay: 10 # (in ms)
#
#  metrics:
#    exporter: otlp
#  logs:
#    exporter: otlp
#  traces:
#    exporter: otlp
#
##  propagators: "tracecontext,baggage,b3"
#  propagators: "tracecontext,baggage"

account:
  service:
    url: http://${ACCOUNT_SERVICE_URL:localhost:8081}