spring:
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:host.docker.internal:9092}
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
  cloud:
    function:
      definition: ${SPRING_CLOUD_FUNCTION_DEFINITION}
    aws:
      dynamodb:
        enabled: true
    openfeign:
      micrometer:
        enabled: true
      okhttp:
        enabled: true

spring.cloud.aws:
  dynamodb:
    endpoint: http://host.docker.internal:4566  # ← LocalStack
  credentials:
    access-key: test
    secret-key: test
  region:
    static: us-east-1

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health
#  endpoint:
#    health:
#      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
#        enabled: true
        enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        spring.kafka.listener: true
        spring.cloud.function: true
        http.client.requests: true
      slo:
        http.client.requests: 50ms,100ms,200ms,500ms,1s,5s
    enable:
#      spring.cloud.function: true
      all: true
#      aws.sdk: true
  tracing:
    enabled: false
    sampling:
      probability: 1.0
  observations:
    annotations:
      enabled: true
#  otlp:
#    logging:
#      export:
#        enabled: true
#      endpoint: ${ALLOY_BASE_URL:http://host.docker.internal:4318}
#    tracing:
#      export:
#        enabled: true
#      endpoint: ${ALLOY_BASE_URL:http://host.docker.internal:4318}
#    metrics:
#      export:
#        enabled: true
#        url: ${ALLOY_BASE_URL:http://host.docker.internal:4318}
#        step: 10s
#otel:
#  service:
#    name: card-service
#  exporter:
#    otlp:
#      endpoint: ${ALLOY_BASE_URL:http://host.docker.internal:4318}
#      protocol: http/protobuf
#      timeout: 2000
#
#  # Configuration for the Batch Span Processor (Traces)
#  bsp:
#    schedule:
#      delay: 1 # (in ms)
#
#  # Configuration for the Batch Log Record Processor (Logs)
#  blrp:
#    schedule:
#      delay: 1 # (in ms)
#
#  metrics:
#    exporter: otlp
#  logs:
#    exporter: otlp
#  traces:
#    exporter: otlp
#
##  propagators: "tracecontext,baggage,b3"
#  propagators: "tracecontext,baggage"

account:
  service:
    url: http://${ACCOUNT_SERVICE_URL:host.docker.internal:8081}


#logging:
#  level:
#    #    org.springframework.boot.context.config.ConfigDataEnvironment: TRACE
#    com.portfolio.banking: INFO
#    org.springframework.kafka: INFO
#    org.apache.kafka: INFO
#    org.springframework.jdbc.datasource: INFO
#    #    io.awspring.cloud.paramstore: DEBUG
#    logging:
#      level:
#        org:
#          hibernate:
#            type:
#              descriptor:
#                sql: INFO
#    feign: DEBUG

#  file:
#    name: /app/logs/card-service.log
#logging:
#  level:
#    org.springframework.beans.factory: DEBUG

