spring:
  application:
    name: card-service
#  config:
#    import: "aws-parameterstore:/banking/backend/account-service/"
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
#  main:
#    web-application-type: none   # Critical for Lambda
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
  cloud:
    function:
      definition: ${SPRING_CLOUD_FUNCTION_DEFINITION}
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      dynamodb:
        endpoint: ${AWS_DYNAMODB_ENDPOINT:}
        enabled: true
    openfeign:
      micrometer:
        enabled: true
      okhttp:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        spring.kafka.listener: true
        spring.cloud.function: true
        http.client.requests: true
      slo:
        http.client.requests: 50ms,100ms,200ms,500ms,1s,5s
    enable:
      all: true
  tracing:
    enabled: false
    sampling:
      probability: 1.0
  observations:
    annotations:
      enabled: true

account:
  service:
    url: http://${ACCOUNT_SERVICE_URL:localhost:8081}