spring:
  application:
    name: CardService
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: card-service-test-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  main:
    web-application-type: none   # Prevents port binding in tests
    allow-bean-definition-overriding: true

spring.cloud.aws:
  credentials:
    access-key: test
    secret-key: test
  region:
    static: us-east-1
  dynamodb:
    endpoint:

server:
  port: 0

account:
  service:
    url: http://${ACCOUNT_SERVICE_URL:localhost:8081}



