spring:
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:host.docker.internal:9092}
  cloud:
    function:
      definition: ${SPRING_CLOUD_FUNCTION_DEFINITION}

spring.cloud.aws:
  dynamodb:
    endpoint: http://host.docker.internal:4566  # ← LocalStack
  credentials:
    access-key: test
    secret-key: test
  region:
    static: us-east-1

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health
#  endpoint:
#    health:
#      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    logging:
      export:
        enabled: true
      endpoint: ${ALLOY_BASE_URL:http://host.docker.internal:4318}/v1/logs
    tracing:
      endpoint: ${ALLOY_BASE_URL:http://host.docker.internal:4318}/v1/traces
    metrics:
      export:
        enabled: true
        url: ${ALLOY_BASE_URL:http://host.docker.internal:4318}/v1/metrics
        step: 10s

account:
  service:
    url: http://${ACCOUNT_SERVICE_URL:host.docker.internal:8081}


#logging:
#  level:
#    #    org.springframework.boot.context.config.ConfigDataEnvironment: TRACE
#    com.portfolio.banking: INFO
#    org.springframework.kafka: INFO
#    org.apache.kafka: INFO
#    org.springframework.jdbc.datasource: INFO
#    #    io.awspring.cloud.paramstore: DEBUG
#    logging:
#      level:
#        org:
#          hibernate:
#            type:
#              descriptor:
#                sql: INFO

#  file:
#    name: /app/logs/card-service.log